concierge/urls.py
from django.conf.urls import url, include
from django.contrib import admin, auth
from django.conf import settings
from django.conf.urls.static import static
import django.contrib.auth.views
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView

from engine.forms import CustomLoginForm, CustomRegForm
from engine.views import RegPage
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^', include('engine.urls')),
    url(r'^login/$',
        auth.views.login,
        {
            'authentication_form': CustomLoginForm,
            'extra_context':
                {
                    'title': _('Sign in'),
                }
        },
        name='login'),
    url(r'^logout/$', auth.views.logout, name='logout'),
    url(r'^register/$', RegPage.as_view(), name='registration_register'),
    url(r'^d10731ac8ae1.html/$', TemplateView.as_view(template_name="engine/pages/d10731ac8ae1.html"), name='yandex'),
    url(r'ckeditor/', include('ckeditor_uploader.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/urls.py
from django.conf.urls import url
from . import views
from geography.views import CitiesView

urlpatterns = [
    url(r'^$', views.MainPage.as_view(), name='main_page'),
    url(r'^services/$', views.AllServices.as_view(), name='all_services'),
    url(r'^category/(?P<cat>[-\w\d]+)/$',
        views.ServicesFromCatList.as_view(), name='cat_service_list'),
    url(r'^services/(?P<country>[-\w\d]+)/$', CitiesView.as_view(),
        name='cities_list'),
    url(r'^services/(?P<country>[-\w\d]+)/(?P<city>[-\w\d]+)/$',
        views.CatsView.as_view(), name='cats_list'),
    url(r'^service/(?P<slug>[-\w\d]+)/$', views.ServiceDetail.as_view(), name='service_detail'),
    url(r'^about-us/$', views.AboutPage.as_view(), name='about_page'),
    url(r'^success/$', views.SuccessPaymentPage.as_view(), name='success_page'),
    url(r'^contacts/$', views.ContactsPage.as_view(), name='contacts_page'),
    url(r'^account/$', views.AccountView.as_view(), name='account_page'),
]

engine/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext as _
from django.db import models
from django.urls import reverse
from django_resized import ResizedImageField

from configs.models import MainPageConfig
from geography.models import City
from ckeditor_uploader.fields import RichTextUploadingField


class User(AbstractUser):
    phone = models.CharField(max_length=15, verbose_name=_("Phone"), blank=True, null=True)


class CatService(models.Model):
    name = models.CharField(max_length=1000, verbose_name=_("Name"), unique=True)
    desc = RichTextUploadingField(verbose_name=_("Description"))
    slug = models.SlugField(max_length=1000, verbose_name=_("Slug"))
    image = ResizedImageField(upload_to='images/cat/%Y/', verbose_name=_("Image"))
    cities = models.ManyToManyField(City, verbose_name=_("City"))

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cat_service_list', kwargs={'cat': self.slug})

    def get_services(self):
        return Service.objects.filter(category=self)


class Service(models.Model):
    category = models.ForeignKey(CatService, verbose_name=_("Category"))
    name = models.CharField(max_length=1000, verbose_name=_("Name"), unique=True)
    desc = RichTextUploadingField(verbose_name=_("Short description"))
    full_desc = RichTextUploadingField(verbose_name=_("Full description"), blank=True, null=True)
    slug = models.SlugField(max_length=1000, verbose_name=_("Slug"))
    image = ResizedImageField(upload_to='images/service/%Y/', verbose_name=_("Image"))
    price = models.PositiveSmallIntegerField(verbose_name=_("Price"))
    cities = models.ManyToManyField(City, verbose_name=_("City"))
    order = models.PositiveSmallIntegerField(verbose_name=_("Output order"), default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('service_detail', kwargs={'slug': self.slug})


class Variation(models.Model):
    service = models.ForeignKey(Service, verbose_name=_("Service"))
    name = models.CharField(max_length=1000, verbose_name=_("Name"))
    price = models.PositiveSmallIntegerField(verbose_name=_("Price"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('variation')
        verbose_name_plural = _("variations")


class Application(models.Model):
    class STATUS:
        ACCEPT = _('Application processed')
        DENY = _('Application denied')
        WAIT = _('Application on moderation')

        CHOICES = (
            (ACCEPT, _('Application processed')),
            (DENY, _('Application denied')),
            (WAIT, _('Application on moderation')),
        )

    user = models.ForeignKey(User, verbose_name=_("User"))
    service = models.ForeignKey(Service, verbose_name=_("Service"))
    check_in = models.DateField(verbose_name=_("Check in"), blank=True, null=True)
    check_out = models.DateField(verbose_name=_("Check out"), blank=True, null=True)
    adults = models.PositiveSmallIntegerField(verbose_name=_("Adults"), blank=True, null=True)
    kids = models.PositiveSmallIntegerField(verbose_name=_("Kids"), blank=True, null=True)
    price_from = models.PositiveSmallIntegerField(verbose_name=_("Price from"))
    price_to = models.PositiveSmallIntegerField(verbose_name=_("Price to"))
    status = models.CharField(max_length=1000, choices=STATUS.CHOICES, default=STATUS.WAIT, verbose_name=_("Status"))
    city = models.ForeignKey(City, verbose_name=_("City"))
    variation = models.ForeignKey(Variation, verbose_name=_("Variation"), null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class GalleryManager(models.Manager):
    def gallery_for_object(self, obj):
        object_type = ContentType.objects.get_for_model(obj)
        return self.filter(content_type__pk=object_type.id,
                           object_id=obj.pk)


class Gallery(models.Model):
    name = models.CharField(max_length=1000, verbose_name=_("Name"))
    image = ResizedImageField(verbose_name=_("Image"), upload_to='images/galleries/')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    objects = GalleryManager()

    class Meta:
        verbose_name = 'image'
        verbose_name_plural = "Gallery"

    def __str__(self):
        return self.name


class Feature(models.Model):
    title = models.CharField(max_length=255, verbose_name=_("Title"))
    desc = models.TextField(verbose_name=_("Description"))
    main_page = models.ForeignKey(MainPageConfig, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

engine/forms.py
from django import forms
from geography.models import City
from .models import Application, User, Service, CatService, Variation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import ugettext as _


class CreateApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = '__all__'
        exclude = ['user', 'service', 'status', 'city']
        widgets = {
            'check_in': forms.DateInput(attrs={'type': 'date'}),
            'check_out': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, variations, *args, **kwargs):
        super(CreateApplicationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].label = _(self.fields[field].label)
        if variations:
            self.fields['variation'] = forms.ModelChoiceField(
                queryset=variations)
            self.fields['variation'].widget.attrs['class'] = 'form-control'
        else:
            self.fields.pop('variation')


class CustomRegForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'phone', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(CustomRegForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].label = _(self.fields[field].label)
        self.fields['username'].widget.attrs.pop('autofocus')


class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].label = _(self.fields[field].label)
        self.fields['username'].widget.attrs.pop('autofocus')


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone',]

    def __init__(self, *args, **kwargs):
        super(AccountEditForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].label = _(self.fields[field].label)

engine/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, DetailView, ListView, CreateView, UpdateView

from configs import models as config
from engine.forms import CreateApplicationForm, AccountEditForm, CustomRegForm
from django.utils.translation import ugettext as _
from engine.models import User, Gallery, Variation, Feature
from geography.models import Country, City
from .models import CatService, Service, Application
from concierge import settings


class MainPage(TemplateView):
    template_name = "engine/pages/index.html"
    config = config.MainPageConfig.objects.get()

    def get_context_data(self, **kwargs):
        context = super(MainPage, self).get_context_data(**kwargs)
        context["services"] = Country.objects.all().order_by("order")
        context["features"] = Feature.objects.all().order_by("id")
        context["title"] = self.config.title
        context[
            'description'] = self.config.desc
        context['banner_img'] = settings.STATIC_URL + 'site/images/frontpage-banner.jpg'
        return context


class CatsView(ListView):
    model = CatService
    template_name = "engine/cats.html"
    city = None

    def dispatch(self, request, *args, **kwargs):
        self.city = City.objects.filter(slug=self.kwargs.get('city')).first()
        request.session['city'] = self.city.slug
        return super(CatsView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = CatService.objects.filter(cities=self.city)
        return qs

    def get_context_data(self, **kwargs):
        context = super(CatsView, self).get_context_data(**kwargs)
        context["title"] = self.city.name
        context['banner_img'] = self.city.image.url
        context['description'] = self.city.full_desc
        return context


class ServicesFromCatList(ListView):
    model = Service
    template_name = "engine/cat_service_list.html"
    cat = None
    city = None

    def dispatch(self, request, *args, **kwargs):
        self.cat = CatService.objects.filter(slug=self.kwargs.get('cat')).first()
        self.city = City.objects.filter(slug=request.session['city']).first()
        return super(ServicesFromCatList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = Service.objects.filter(category=self.cat, cities=self.city)
        return qs

    def get_context_data(self, **kwargs):
        context = super(ServicesFromCatList, self).get_context_data(**kwargs)
        context["title"] = self.cat.name
        context['description'] = self.cat.desc
        context['banner_img'] = self.cat.image.url
        return context


class AllServices(ListView):
    model = Country
    template_name = "engine/all_services.html"

    def get_context_data(self, **kwargs):
        context = super(AllServices, self).get_context_data(**kwargs)
        context["title"] = _("Services")
        return context


class ServiceDetail(DetailView, CreateView):
    model = Service
    form_class = CreateApplicationForm
    template_name = 'engine/service_detail.html'
    success_url = '/success'
    variations = None

    def dispatch(self, request, *args, **kwargs):
        self.variations = Variation.objects.filter(service=self.get_object().pk)
        return super(ServiceDetail, self).dispatch(request, *args, **kwargs)

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.variations, **self.get_form_kwargs())

    def get_context_data(self, **kwargs):
        context = super(ServiceDetail, self).get_context_data(**kwargs)
        context["title"] = self.object.name
        context['description'] = self.object.desc
        context['banner_img'] = self.object.image.url
        context['gallery'] = Gallery.objects.gallery_for_object(self.get_object())
        context['variations'] = self.variations
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.service = self.get_object()
        form.instance.city = City.objects.filter(slug=self.request.session['city']).first()
        return super(ServiceDetail, self).form_valid(form)


class AboutPage(TemplateView):
    template_name = "engine/pages/about-us.html"
    config = config.AboutUsPageConfig.objects.get()

    def get_context_data(self, **kwargs):
        context = super(AboutPage, self).get_context_data(**kwargs)
        context["title"] = self.config.title
        context[
            'description'] = self.config.desc
        return context


class ContactsPage(TemplateView):
    template_name = "engine/pages/contacts.html"

    def get_context_data(self, **kwargs):
        context = super(ContactsPage, self).get_context_data(**kwargs)
        context["title"] = _("Contacts")
        return context


class SuccessPaymentPage(TemplateView):
    template_name = "engine/pages/success.html"

    def get_context_data(self, **kwargs):
        context = super(SuccessPaymentPage, self).get_context_data(**kwargs)
        context["title"] = _("Success")
        return context


# class RegPage(RegistrationView):
#     def get_context_data(self, **kwargs):
#         context = super(RegPage, self).get_context_data(**kwargs)
#         context['title'] = 'Registration'
#         return context


class RegPage(CreateView):
    model = User
    form_class = CustomRegForm
    template_name = 'registration/registration_form.html'
    success_url = '/login'

    def get_context_data(self, **kwargs):
        context = super(RegPage, self).get_context_data(**kwargs)
        context['title'] = _('Registration')
        return context


class AccountView(UpdateView):
    template_name = "engine/pages/account.html"
    model = User
    form_class = AccountEditForm
    success_url = "."

    @method_decorator(login_required())
    def dispatch(self, request, *args, **kwargs):
        return super(AccountView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AccountView, self).get_context_data(**kwargs)
        context["title"] = _("Account")
        context["applications"] = Application.objects.filter(user=self.get_object())
        return context

    def get_object(self, queryset=None):
        return auth.get_user(self.request)

templates/engine/all_services.html
{% extends "engine/parts/base.html" %}
{% load i18n %}
{% block content %}
    <div id="fh5co-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
                    <h2>{% trans 'Select country' %}</h2>
                </div>
            </div>
            <div class="card-deck row-bottom-padded-md justify-content-center">
                {% for country in country_list %}
                    <div class="col-sm-5">
                        <div class="fh5co-blog animate-box">
                            <a href="{{ country.get_absolute_url }}"><img class="img-responsive"
                                                                          src="{{ country.image.url }}" alt=""></a>
                            <div class="blog-text">
                                <h3><a href="{{ country.get_absolute_url }}">{{ country.name }}</a></h3>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/engine/cat_service_list.html
{% extends "engine/parts/base.html" %}
{% load i18n %}
{% block content %}
    {% if service_list %}
    <div id="fh5co-blog">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
					<h2>{% trans 'Select service' %}</h2>
				</div>
			</div>
			<div class="card-deck row-bottom-padded-md justify-content-center">
                {% for service in service_list %}
				<div class="col-sm-4">
					<div class="fh5co-blog animate-box">
						<a href="{{ service.get_absolute_url }}"><img class="img-responsive" src="{{ service.image.url }}" alt=""></a>
						<div class="blog-text">
							<h3><a href="{{ service.get_absolute_url }}">{{ service.name }}</a></h3>
							<span class="posted_on">{% trans 'Price from' %}: {{ service.price }}$</span>
						</div>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</div>
    {% endif %}
{% endblock %}

templates/engine/cats.html
{% extends "engine/parts/base.html" %}
{% load i18n %}
{% block content %}
    {% if catservice_list %}
    <div id="fh5co-blog">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
					<h2>{% trans 'Choose category' %}</h2>
				</div>
			</div>
			<div class="card-deck row-bottom-padded-md justify-content-center">
                {% for cat in catservice_list %}
				<div class="col-sm-4">
					<div class="fh5co-blog animate-box">
						<a href="{{ cat.get_absolute_url }}"><img class="img-responsive" src="{{ cat.image.url }}" alt=""></a>
						<div class="blog-text">
							<h3><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></h3>
						</div>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</div>
    {% endif %}
{% endblock %}

templates/engine/cities.html
{% extends "engine/parts/base.html" %}
{% load i18n %}
{% block content %}
    {% if city_or_state_list %}
    <div id="fh5co-blog">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
					<h2>{% trans 'Choose your city' %}</h2>
				</div>
			</div>
			<div class="card-deck row-bottom-padded-md justify-content-center">
                {% for cs in city_or_state_list %}
				<div class="col-sm-4">
					<div class="fh5co-blog animate-box">
						<a href="{{ cs.get_absolute_url }}"><img class="img-responsive" src="{{ cs.image.url }}" alt=""></a>
						<div class="blog-text">
							<h3><a href="{{ cs.get_absolute_url }}">{{ cs.name }}</a></h3>
						</div>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</div>
    {% endif %}
{% endblock %}

templates/engine/service_detail.html
{% extends "engine/parts/base.html" %}
{% load i18n %}
{% block content %}
    <div class="fh5co-abstract">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
                    <h2>{% trans 'Description' %}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 animate-box">
                    <p>{{ service.full_desc|safe }}</p>
                </div>
            </div>
            {% if gallery %}
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
                    <h2>{% trans 'Gallery' %}</h2>
                </div>
            </div>
            <div class="row row-bottom-padded-md">
                <div class="col-md-12">
                    <ul id="fh5co-portfolio-list">
                        {% for image in gallery %}
                        <li class="one-third animate-box fast" data-animate-effect="fadeIn"
                            style="background-image: url('{{ image.image.url }}'); ">
                            <a href="{{ image.image.url }}" data-lightbox="roadtrip"></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
                    <h2>{% trans 'Send application' %}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 animate-box">
                    {% if user.is_authenticated %}
                        <form action="" class="form-horizontal" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                {% for field in form %}
                                    <div class="col-md-6">
                                        {% if field.errors %}
                                            <div class="alert alert-danger" role="alert">
                                                {{ field.errors }}
                                            </div>
                                        {% endif %}
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        {% if field.help_text %}
                                            {{ field.help_text }}
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </div>
                            <p class="lead">{% trans 'Total amount' %}: <span id="price">{{ service.price }}</span>$</p>
                            <input type="submit" class="btn btn-primary" value="{% trans 'Checkout' %}">
                        </form>
                        <table style="display: none;">
                            {% for var in variations %}
                                <tr>
                                    <td id="{{ var.id }}">{{ var.price }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        <div class="alert alert-info">
                            <p><a href="{% url 'login' %}" class="alert-link">{% trans 'Login' %}</a> or <a href="{% url 'registration_register' %}" class="alert-link">{% trans 'register' %}</a> {% trans 'to send an application' %}.</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}